'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8745
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("resto.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property img_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_46() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_46", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_49() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_49", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img46() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img46", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img49() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img49", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
